"""schema inicial 19 tablas plan s10

Revision ID: 2745087c7ff9
Revises: 
Create Date: 2026-09-27 04:09:15.478377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2745087c7ff9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categorias_id'), 'categorias', ['id'], unique=False)
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('nit', sa.String(), nullable=True),
    sa.Column('sector', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empresas_id'), 'empresas', ['id'], unique=False)
    op.create_index(op.f('ix_empresas_nit'), 'empresas', ['nit'], unique=True)
    op.create_table('matrices_datos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_matriz', sa.String(), nullable=True),
    sa.Column('valores', sa.JSON(), nullable=False),
    sa.Column('dimensiones', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrices_datos_id'), 'matrices_datos', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('permisos', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_table('vectores_datos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_vector', sa.String(), nullable=True),
    sa.Column('valores', sa.JSON(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vectores_datos_id'), 'vectores_datos', ['id'], unique=False)
    op.create_table('matrix_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matriz_id', sa.Integer(), nullable=True),
    sa.Column('fila', sa.Integer(), nullable=False),
    sa.Column('columna', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['matriz_id'], ['matrices_datos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matrix_values_id'), 'matrix_values', ['id'], unique=False)
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('precio_base', sa.Float(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index(op.f('ix_productos_id'), 'productos', ['id'], unique=False)
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=True),
    sa.Column('codigo_sucursal', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_sucursal')
    )
    op.create_index(op.f('ix_sucursales_id'), 'sucursales', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('vector_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.Integer(), nullable=True),
    sa.Column('posicion', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vector_id'], ['vectores_datos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vector_values_id'), 'vector_values', ['id'], unique=False)
    op.create_table('auditoria_eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(), nullable=True),
    sa.Column('modulo', sa.String(), nullable=True),
    sa.Column('detalle', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_eventos_id'), 'auditoria_eventos', ['id'], unique=False)
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('stock_actual', sa.Float(), nullable=True),
    sa.Column('stock_minimo', sa.Float(), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventario_id'), 'inventario', ['id'], unique=False)
    op.create_table('math_operation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion', sa.String(), nullable=True),
    sa.Column('entrada_a', sa.JSON(), nullable=True),
    sa.Column('entrada_b', sa.JSON(), nullable=True),
    sa.Column('resultado', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_math_operation_logs_id'), 'math_operation_logs', ['id'], unique=False)
    op.create_table('metas_empresariales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('valor_meta', sa.Float(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=True),
    sa.Column('fecha_limite', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metas_empresariales_id'), 'metas_empresariales', ['id'], unique=False)
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('monto_total', sa.Float(), nullable=True),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ventas_id'), 'ventas', ['id'], unique=False)
    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('detalle', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['inventario_id'], ['inventario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_table('operation_inputs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion_id', sa.Integer(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('valor', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['operacion_id'], ['math_operation_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_inputs_id'), 'operation_inputs', ['id'], unique=False)
    op.create_table('operation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operacion_id', sa.Integer(), nullable=True),
    sa.Column('valor', sa.JSON(), nullable=True),
    sa.Column('formato', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['operacion_id'], ['math_operation_logs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operation_results_id'), 'operation_results', ['id'], unique=False)
    op.create_table('sale_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=True),
    sa.Column('producto_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_details_id'), 'sale_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sale_details_id'), table_name='sale_details')
    op.drop_table('sale_details')
    op.drop_index(op.f('ix_operation_results_id'), table_name='operation_results')
    op.drop_table('operation_results')
    op.drop_index(op.f('ix_operation_inputs_id'), table_name='operation_inputs')
    op.drop_table('operation_inputs')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_table('inventory_movements')
    op.drop_index(op.f('ix_ventas_id'), table_name='ventas')
    op.drop_table('ventas')
    op.drop_index(op.f('ix_metas_empresariales_id'), table_name='metas_empresariales')
    op.drop_table('metas_empresariales')
    op.drop_index(op.f('ix_math_operation_logs_id'), table_name='math_operation_logs')
    op.drop_table('math_operation_logs')
    op.drop_index(op.f('ix_inventario_id'), table_name='inventario')
    op.drop_table('inventario')
    op.drop_index(op.f('ix_auditoria_eventos_id'), table_name='auditoria_eventos')
    op.drop_table('auditoria_eventos')
    op.drop_index(op.f('ix_vector_values_id'), table_name='vector_values')
    op.drop_table('vector_values')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_sucursales_id'), table_name='sucursales')
    op.drop_table('sucursales')
    op.drop_index(op.f('ix_productos_id'), table_name='productos')
    op.drop_table('productos')
    op.drop_index(op.f('ix_matrix_values_id'), table_name='matrix_values')
    op.drop_table('matrix_values')
    op.drop_index(op.f('ix_vectores_datos_id'), table_name='vectores_datos')
    op.drop_table('vectores_datos')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_matrices_datos_id'), table_name='matrices_datos')
    op.drop_table('matrices_datos')
    op.drop_index(op.f('ix_empresas_nit'), table_name='empresas')
    op.drop_index(op.f('ix_empresas_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index(op.f('ix_categorias_id'), table_name='categorias')
    op.drop_table('categorias')
    # ### end Alembic commands ###
